version: "3.9"

networks:
  default:
    external:
      name: local_volue

services:

  sql-server-db:
    container_name: volue-sql-server-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "5433:1433"
    networks:
      default:
        ipv4_address: 10.6.0.11
    environment:
      SA_PASSWORD: "SA_password123"
      ACCEPT_EULA: "Y"